### ISSUE TITLE
Hosting auf der VM

### ISSUE THREAD

**Issue by Marcus-Rabeder** [SYP-AHIF-2023-24-25/Leofee#72]
- Backend + Datenbank läuft auf der VM
- Admin dashboard ist über die VM erreichbar
- Unterscheidung von Produktion und Development Mode, für das backend

**Comment by SamuelAtzi** [comment]
Die datenbank mit dem Backend läuft erfolgreich auf der VM, 
Bei der dashboard anwendung, gibt es noch probleme
